/* =========================================
   Fake server for this task.
   It behaves like a real API: responses are slow,
   different endpoints take different amounts of time,
   and some requests can fail.

   DO NOT EDIT THIS FILE. Fix the bugs in main.js and styles.css.
   ========================================= */

(function () {
  const PRODUCTS = [
    { id: 'p1', name: 'Fold Sofa', category: 'seating', price: 38999, color: '#c9a88a',
      description: 'A two-seater that folds out into a guest bed in under ten seconds. Removable, washable covers in four colours, and a frame built to handle daily unfolding for years.' },
    { id: 'p2', name: 'Stack Shelf', category: 'storage', price: 7499, color: '#a9b8a3',
      description: 'Modular shelving you can stack.' },
    { id: 'p3', name: 'Arc Floor Lamp', category: 'lighting', price: 5999, color: '#e2c290',
      description: 'Warm, dimmable light that curves over a sofa or reading chair without taking up floor space.' },
    { id: 'p4', name: 'Perch Stool', category: 'seating', price: 3299, color: '#b7a38f',
      description: 'Solid oak, stackable.' },
    { id: 'p5', name: 'Slim Console', category: 'storage', price: 11999, color: '#9fa9b3',
      description: 'Only 24 cm deep, so it fits behind a sofa or in a narrow hallway. Two hidden drawers keep keys, chargers and mail out of sight.' },
    { id: 'p6', name: 'Glow Pendant', category: 'lighting', price: 4499, color: '#e8d3a8',
      description: 'Paper pendant with a soft, even glow.' },
    { id: 'p7', name: 'Nest Armchair', category: 'seating', price: 18499, color: '#caa596',
      description: 'Deep seat, low arms and a compact footprint. Designed for corners that usually end up empty.' },
    { id: 'p8', name: 'Cube Drawers', category: 'storage', price: 6299, color: '#b3b09a',
      description: 'Three drawers, one small cube. Works as a bedside table, a desk add-on or entryway storage.' },
    { id: 'p9', name: 'Duo Bench', category: 'seating', price: 8999, color: '#bfa58c',
      description: 'Seats two at the table, stores shoes by the door.' },
    { id: 'p10', name: 'Dot Table Lamp', category: 'lighting', price: 2999, color: '#dccb9c',
      description: 'Rechargeable, cordless and small enough to carry from desk to balcony. Lasts about 12 hours on one charge.' }
  ];

  // Each category is served from a different "cache", so response times differ.
  const DELAYS = { all: 500, seating: 1500, storage: 400, lighting: 900 };
  const PER_PAGE = 4;
  const TAKEN_EMAILS = ['taken@example.com', 'hello@nookstudio.com'];

  let cartCount = 0;
  let flakyPageFailed = false;

  function wait(ms) {
    return new Promise(function (resolve) { setTimeout(resolve, ms); });
  }

  window.NookAPI = {
    /**
     * Returns { items: Product[], page: number, hasMore: boolean }
     * Rejects with an Error on a network failure.
     */
    async getProducts({ category = 'all', page = 1 } = {}) {
      await wait(DELAYS[category] || 600);

      // Simulated flaky network: the first request for page 3 of "all" fails.
      if (category === 'all' && page === 3 && !flakyPageFailed) {
        flakyPageFailed = true;
        throw new Error('Network error: request timed out');
      }

      const list = category === 'all'
        ? PRODUCTS
        : PRODUCTS.filter(function (p) { return p.category === category; });

      const start = (page - 1) * PER_PAGE;
      const items = list.slice(start, start + PER_PAGE);

      return {
        items: items,
        page: page,
        hasMore: start + PER_PAGE < list.length
      };
    },

    /**
     * Returns { count: number } (total items in cart after adding)
     */
    async addToCart(productId) {
      await wait(700);
      cartCount += 1;
      return { count: cartCount, productId: productId };
    },

    /**
     * Returns { ok: true, message } or { ok: false, message }
     */
    async subscribe(email) {
      await wait(1200);
      const clean = String(email || '').trim().toLowerCase();

      if (!clean || !clean.includes('@')) {
        return { ok: false, message: 'Please enter a valid email address.' };
      }
      if (TAKEN_EMAILS.includes(clean)) {
        return { ok: false, message: 'This email is already subscribed.' };
      }
      return { ok: true, message: 'You are in! Check your inbox for your 10% code.' };
    }
  };
})();
